### ISSUE TITLE
Is string.Empty a valid argument for the User constructor?

### ISSUE THREAD

**Issue by camiller2** [configcat/.net-sdk#11]
What are valid values for the `identifier` argument in the `User` constructor? Specifically, is `string.Empty` valid, or will this result in unexpected behavior? I partly ask because the Java SDK appears to throw an exception when passing `""` whereas this .NET SDK does not.

Also, would you consider making a parameterless constructor for `User`? Our use case is such that we only care about evaluating rules based on custom attributes, not user ids. 

Thanks in advance.

**Comment by endret** [comment]
> What are valid values for the `identifier` argument in the `User` constructor? Specifically, is `string.Empty` valid, or will this result in unexpected behavior? I partly ask because the Java SDK appears to throw an exception when passing `""` whereas this .NET SDK does not.
> 
> Also, would you consider making a parameterless constructor for `User`? Our use case is such that we only care about evaluating rules based on custom attributes, not user ids.
> 
> Thanks in advance.


Hi,

When you use net-sdk you can pass empty string or null to the user's identifier. If you are not planning to use feature targeting by percentage just pass same value of string, but with this implementation you can not use percentage based targeting in the future.
We are not planning to introduce parameterless constructor but actually we're working on ensuring unique User object behaviour. The expected mechanism will allow null, empty string in all SDK.

Kind regards,

E.

**Comment by endret** [comment]
The following release fix it: [v5.3.77](https://github.com/configcat/.net-sdk/releases/tag/v5.3.77)
