### ISSUE TITLE
Provide change notifications in the .Net client

### ISSUE THREAD

**Issue by jochenz** [configcat/.net-sdk#25]
We use ConfigCat for feature flags and for dynamic configuration in general. Most values are consulted on a per-request basis, but some configuration values apply to the entire host process (e.g. a minimum thread count for the thread pool).

Since these values are not evaluated per request, it would be nice to subscribe to change notifications for these values.

### Describe the solution you'd like

We're using ConfigCat in auto polling mode. The client could look for changes in the config every time it receives a new config and raise a .Net event for every changed value.

**Comment by laliconfigcat** [comment]
Hello @jochenz ,

We already have a change notification built into the SDK in case of the auto polling mode: 
https://configcat.com/docs/sdk-reference/csharp#auto-polling-default
https://github.com/configcat/.net-sdk/blob/master/src/ConfigCatClient/Configuration/AutoPollConfiguration.cs#L31

It is basically calling the event in case of the underlying config.json changes in any way. 
I would use it in a way like this:
```
var myCurrentValue = ...;
var clientConfiguration = new AutoPollConfiguration
    {
        SdkKey = "#YOUR-SDK-KEY#"
    };

IConfigCatClient client = new ConfigCatClient(clientConfiguration);

clientConfiguration.OnConfigurationChanged += (sender, args) => 
    {
        var newValue = client.GetValue('key', ...));
        if ((newValue != myCurrentValue) 
        {
             myCurrentValue = newValue;
             // do the necessary things.
        }
    };
```

What do you think?

Cheers,
Lali

**Comment by jochenz** [comment]
Ok, that was a little hidden ;-)

Not in the IConfigCatClient interface, but in the configuration to create the client... Overlooked that one.

**Comment by laliconfigcat** [comment]
Yes, because it can only be used in the Auto polling mode and we didn't want to confuse our customers with this on the IConfigCatClient itself.
I hope you'll be able to use it.

**Comment by jochenz** [comment]
I see. Makes perfect sense then :-)

Yes, we will be able to use it!
