### ISSUE TITLE
Requesting removal of Newtonsoft.Json

### ISSUE THREAD

**Issue by magkal** [configcat/.net-sdk#30]
### Is your feature request related to a problem? 

Yes and no 🙃

### Describe the solution you'd like

I'd like to see the dependency to `Newtonsoft.Json` removed in favor of `System.Text.Json` and perhaps a compiled version targeting dotnet 6, to get full benefits of the latest framework version.

### Additional context

Newtonsoft.Json is extremely slow compared to modern json libraries, It's also nice if we can get a smaller list of dependencies into our solution. Considering the launch of dotnet5 last year, Newtonsoft is no longer the go-to solution for handling json in dotnet, unless there is a feature gap that is too hard to re-implement with System.Text.Json.

**Comment by z4kn4fein** [comment]
Hey @magkal,

Thanks for reaching out! We have plans to make some improvements here in the near future. I don't see any blockers in your suggestions so we'll try to include them for sure.

**Comment by z4kn4fein** [comment]
Hi @magkal, we added `net6.0` in the latest release and the SDK now uses `System.Text.Json` with each target except `net45`.
