### ISSUE TITLE
New Release with LoggerWrapper fix #39

### ISSUE THREAD

**Issue by cristobal** [configcat/.net-sdk#40]
### Is your feature request related to a problem? Please describe.

We set logger level = Error, but we still get some Debug output.
<img width="345" alt="Screenshot 2022-09-06 at 12 30 45" src="https://user-images.githubusercontent.com/155505/188613324-448141f9-a036-4411-a8b1-6120968b0392.png">

I deep dived into the decompiled code and saw the issue, however when checking out the code i saw that the issue already has been solved via #39 

### Describe the solution you'd like

A new release of the .net-sdk with the logger wrapper fix, i guess this just was overlooked or perhaps you have some release cycle that you are following.

### Describe alternatives you've considered

Just wait for a new release with the fix 🙏🏽 
Thanks in advance 👋🏽

**Comment by endret** [comment]
Hi @cristobal ,

Thank you for reporting.

Can you send us the code snippet with configcat client initialization (please mask your SDK key)?

Thanks,
Endre

**Comment by z4kn4fein** [comment]
Hi @cristobal, the changes you mentioned were released in v6.5.3

**Comment by cristobal** [comment]
> Hi @cristobal, the changes you mentioned were released in v6.5.3

Yeah i can confirm that this works as expected in version `v6.5.3`, when i set the default log level to Error we no longer receive any debug output 👍🏽 

![Screenshot 2022-09-07 at 23 04 58](https://user-images.githubusercontent.com/155505/188980093-458e08bd-b30f-44e3-9247-2a2c1e9e85d9.png)
