### ISSUE TITLE
ConfigCat.Client makes a lot of requests

### ISSUE THREAD

**Issue by benclerix-cegeka** [configcat/.net-sdk#7]
Hi,

We use ConfigCat.Client Version 2.2.1.
We notice a lot of calls happening within the same operation.
Most of them (1153) return with a HTTP statuscode 304 Not Modified  and some (289) return with a 200 OK.
Still we would not expect this many calls within the same operation.
How could we provide you with more information to help debug this issue?

**Comment by configcat** [comment]
Hello,

Could you please describe the time range for these calls? What do you mean on the same operation? 
In which mode are you using the ConfigCat SDK (auto poll, manual poll, lazy loading) and how did you setup the SDK?

As the v2.2.1 is way more behind the current stable version (v4.0.36) we strongly recommend you to update to the newest one. We are writing about the supported SDK versions in our [SLA](https://configcat.com/sla): "a version which is behind more than one major or minor version than the current version".

Also it could be easier for us to investigate this problem with direct messaging. Could you please join our [community slack channel](https://join.slack.com/t/configcat-community/shared_invite/enQtMzkwNDg3MjQ3MTUyLWY1ZmE0NjY5NjA0YjAzMWU3MDg3ODhkMGI2ZjdmZjZmYTY4YTg1NmQ0YzBhMTVhOGE5YmNiYTI5OTg4NmNjYTQ) and reach back to me (Lajos from Configcat) there? 

Cheers,
Lajos

**Comment by benclerix-cegeka** [comment]
Hi,

After some more investigating it seems that our logging is incorrect.
We'll update to a later version of the SDK and get back to you.
