### ISSUE TITLE
Change  IConfigCatClient.Snapshot() to return IConfigCatClientSnapshot

### ISSUE THREAD

**Issue by brian-knoll-micronetonline** [configcat/.net-sdk#92]
### Is your feature request related to a problem? Please describe.

I am having increased difficulty testing my code that uses IConfigCatClient.Snapshot()

### Describe the solution you'd like

Change ` IConfigCatClient.Snapshot()` to return `IConfigCatClientSnapshot`

### Describe alternatives you've considered

Testing in a way that does not Moq the result of Snapshot

### Additional context

Seems like an oversight as this project seems to use interfaces in plenty of places already

**Comment by adams85** [comment]
Hey @brian-knoll-micronetonline,

> Seems like an oversight as this project seems to use interfaces in plenty of places already

It's not an oversight, it was a deliberate design choice to make the result type of  `IConfigCatClient.Snapshot()` a value type, for performance considerations (to avoid heap memory allocation).

The `ConfigCatClientSnapshot` type, however, [provides a constructor](https://github.com/configcat/.net-sdk/blob/v9.2.0/src/ConfigCatClient/ConfigCatClientSnapshot.cs#L32) that takes an `IConfigCatClientSnapshot` object as its parameter. This should allow you to provide a fake implementation for testing purposes.

Does this work for you? If not, what difficulties do you experience exactly with your tests?

**Comment by brian-knoll-micronetonline** [comment]
That works for my use case thank you
